import './core/config.js';
import './core/state.js';
import './core/events.js';
import './core/canvas.js';
import './core/input.js';
import './core/game-loop.js';
import './simulation/point.js';
import './simulation/spring.js';
import './simulation/cloth.js';
import './simulation/physics.js';
import './render/renderer.js';
import './render/effects-renderer.js';
import './render/fire-gpu-renderer.js';
import './particles/particle.js';
import './particles/fire-particle.js';
import './particles/particle-system.js';
import './fire/fire-system.js';
import './tools/tool-manager.js';
import './tools/tool-effects.js';
import './tools/mouse-tool.js';
import './tools/blower-tool.js';
import './tools/cannon-tool.js';
import './tools/dart-tool.js';
import './tools/flame-tool.js';
import './tools/blade-tool.js';
import './tools/hook-tool.js';
import './tools/drill-tool.js';
import './tools/laser-tool.js';
import './tools/scissor-tool.js';
import './tools/hammer-tool.js';
import './tools/acid-tool.js';
import './tools/glue-tool.js';
import './tools/electric-tool.js';
import './missions/mission-data.js';
import './missions/mission-system.js';
import './entities/cannonball.js';
import './entities/dart.js';
import './progression/player-data.js';
import './progression/xp-system.js';
import './progression/upgrade-system.js';
import './progression/ability-system.js';
import './progression/abilities-data.js';
import './ui/dom.js';
import './ui/hud.js';
import './ui/toolbar.js';
import './ui/config-modal.js';
import './ui/upgrade-modal.js';
import './ui/special-modal.js';
import './ui/abilities-bar.js';
import './storage/save-system.js';
import './utils/math.js';
import './utils/constants.js';
import { bootGame } from './app/game-runtime.js';

function boot() {
    bootGame();
}

boot();
