const baseConfig = {
    numeroDeLinhas: 30,
    spacing: 12,
    stiffness: 0.9,
    gravity: 0.4,
    friction: 0.99,
    tearDistance: 50,
    lineWidth: 0.5,
    lineColor: '#55aaff',
    flameIntensity: 1.0,
    debugPerformance: false,
    physicsAdaptive: {
        enabled: true,
        maxIterations: 5,
        minIterations: 2,
        stableIterations: 2,
        normalIterations: 3,
        activeIterations: 5,
        stabilityVelocityThreshold: 0.18,
        stabilityMotionThreshold: 0.22,
        highStressThreshold: 0.18,
        activeCooldownFrames: 45,
        sampleEveryFrames: 6,
        debug: false,
    },
    rendering: {
        clothRenderer: 'gpu',
        gpuFallback: true,
        gpuRenderFabric: true,
        gpuRenderLines: true,
        gpuRenderPoints: false,
        debugGpuRenderer: false,
        debugGpuLineDirty: false,
        gpuTopologyUpdateMode: 'dirty',
        gpuLineTopologyUpdateMode: 'dirty',
    },
    testRender: {
        gpuRenderLines: true,
        gpuRenderPoints: false,
    },
    materialPattern: 'targetShield',
    clothVisual: {
        mode: 'fabric',
        material: 'mixed',
        category: 'mixed',
        fabricFillAlpha: 1,
        fabricLineAlpha: 0.08,
        fabricPointAlpha: 0.0,
        renderFabricMesh: true,
        renderFabricPoints: false,
        fabricTextureTilesX: 2,
        fabricTextureTilesY: 2,
        useFastMeshRender: true,
        useCachedCellColors: true,
    },
    materials: {
        cloth: {
            name: 'Tecido',
            pointHpMultiplier: 1,
            springHpMultiplier: 1,
            fireResistance: 1,
            slashResistance: 1,
            impactResistance: 1,
            pierceResistance: 1,
            tensionResistance: 1,
            chemicalResistance: 1,
            electricResistance: 1,
            elasticityMultiplier: 1,
            color: '#55aaff',
        },
        paper: {
            name: 'Papel',
            pointHpMultiplier: 0.55,
            springHpMultiplier: 0.55,
            fireResistance: 0.35,
            slashResistance: 0.75,
            impactResistance: 0.8,
            pierceResistance: 0.8,
            tensionResistance: 0.7,
            chemicalResistance: 0.9,
            electricResistance: 1.15,
            elasticityMultiplier: 0.85,
            color: '#d8d2bd',
        },
        leather: {
            name: 'Couro',
            pointHpMultiplier: 1.6,
            springHpMultiplier: 1.5,
            fireResistance: 1.7,
            slashResistance: 1.35,
            impactResistance: 1.1,
            pierceResistance: 1.2,
            tensionResistance: 1.0,
            chemicalResistance: 0.65,
            electricResistance: 1.2,
            elasticityMultiplier: 0.8,
            color: '#8b5a2b',
        },
        rubber: {
            name: 'Borracha',
            pointHpMultiplier: 1.3,
            springHpMultiplier: 1.3,
            fireResistance: 1.2,
            slashResistance: 1.1,
            impactResistance: 1.6,
            pierceResistance: 1.0,
            tensionResistance: 1.3,
            chemicalResistance: 0.55,
            electricResistance: 1.35,
            elasticityMultiplier: 1.7,
            color: '#222222',
        },
        metalMesh: {
            name: 'Malha Metalica',
            pointHpMultiplier: 2.2,
            springHpMultiplier: 2.4,
            fireResistance: 999,
            slashResistance: 2.4,
            impactResistance: 1.7,
            pierceResistance: 1.8,
            tensionResistance: 1.5,
            chemicalResistance: 3.5,
            electricResistance: 0.45,
            elasticityMultiplier: 0.55,
            color: '#aab7c4',
        },
        reinforced: {
            name: 'Costura Reforcada',
            pointHpMultiplier: 2,
            springHpMultiplier: 2.2,
            fireResistance: 1.6,
            slashResistance: 1.8,
            impactResistance: 1.4,
            pierceResistance: 1.4,
            tensionResistance: 1.8,
            chemicalResistance: 0.7,
            electricResistance: 0.8,
            elasticityMultiplier: 0.7,
            color: '#ffd166',
        },
    },
    layers: {
        outer: {
            index: 0,
            name: 'Externa',
            hpMultiplier: 0.85,
            damageMultiplier: 1.1,
            coverageWeight: 1,
            colorTint: 0.08,
        },
        middle: {
            index: 1,
            name: 'Media',
            hpMultiplier: 1.15,
            damageMultiplier: 1,
            coverageWeight: 1.3,
            colorTint: 0,
        },
        inner: {
            index: 2,
            name: 'Interna',
            hpMultiplier: 1.45,
            damageMultiplier: 0.85,
            coverageWeight: 1.7,
            colorTint: -0.08,
        },
    },
    clothDamage: {
        pointBaseHp: 160,
        springBaseHp: 180,
        pointArmor: 2,
        springArmor: 2,
        springSafeStrain: 1.85,
        springCriticalStrain: 2.45,
        tensionDamageMultiplier: 0.035,
        tensionDamageMinStrain: 1.85,
        tensionDamageMaxPerFrame: 0.35,
        startupInvulnerabilityFrames: 120,
        gravityTensionDamageScale: 0.15,
        mouseSlashDamage: 8,
        cannonImpactDamage: 20,
        cannonImpactRadius: 75,
        dartPierceDamage: 14,
        flameDamagePerTick: 0.22,
        explosionDamage: 35,
        explosionRadius: 110,
        damageVisualThreshold1: 0.25,
        damageVisualThreshold2: 0.55,
        damageVisualThreshold3: 0.8,
        minDamageToShowEffect: 2,
    },
    targetConfig: {
        enabled: true,
        radius: 90,
        hp: 300,
        exposedThreshold: 20,
        coverageUpdateInterval: 12,
    },
    damageEffectsConfig: {
        maxDamageParticles: 300,
        maxBurstParticles: 35,
        impactRingLife: 28,
        fiberParticleLife: 35,
        enableGlow: true,
        enableImpactRings: true,
        enableFiberParticles: true,
    },
    fireGpuRenderer: {
        enabled: true,
        fallbackToCanvas: true,
        maxParticles: 1200,
        particleScale: 1.0,
        smokeScale: 1.0,
        glowStrength: 1.0,
        useAdditiveBlending: true,
        renderSmoke: true,
        renderFire: true,
        debug: false,
    },
    fire: {
        maxParticles: 1200,
        maxNewParticlesPerFrame: 80,
        particleCullBatchSize: 300,
    },
    background: {
        enabled: true,
        style: 'testChamber',
        renderGrid: true,
        renderPanels: true,
        renderHazardStripes: true,
        renderTargetGhost: true,
        renderDirt: true,
        cacheStaticLayer: true,
    },
    decals: {
        enabled: true,
        maxDecals: 220,
        maxSmokeParticles: 90,
        persistent: true,
        fadeOldDecals: false,
        burnMarks: true,
        acidMarks: true,
        impactMarks: true,
        slashMarks: true,
        explosionMarks: true,
        bulletMarks: true,
        heatGlow: true,
    },
    decalSpawnCooldowns: {
        burn: 180,
        acid: 220,
        laser: 80,
        slash: 60,
        stab: 90,
        hammer: 120,
        explosion: 0,
        electric: 90,
        glue: 140,
    },
    bladeTool: {
        radius: 18,
        baseDamage: 7,
        speedDamageMultiplier: 0.035,
        criticalBreakBonus: 1.5,
        maxDamagePerFrame: 16,
        sparkChance: 0.25,
    },
    hookTool: {
        attachRadius: 28,
        pullStrength: 0.35,
        maxPullForce: 18,
        tensionDamageMultiplier: 0.08,
        detachDistance: 260,
        visualRopeWidth: 2,
    },
    drillTool: {
        radius: 22,
        pointDamagePerFrame: 0.65,
        springDamagePerFrame: 0.55,
        heatBuildUp: 0.35,
        maxParticlesPerFrame: 5,
    },
    laserTool: {
        length: 130,
        width: 10,
        damagePerFrame: 0.42,
        heatPerFrame: 0.35,
        igniteChance: 0.02,
        maxHitSpringsPerFrame: 20,
    },
    scissorTool: {
        selectRadius: 16,
        damage: 42,
        criticalBonus: 1.4,
        preview: true,
    },
    hammerTool: {
        radius: 70,
        damage: 14,
        impulse: 14,
        cooldownMs: 250,
        shockwaveLife: 22,
    },
    acidTool: {
        radius: 48,
        damagePerTick: 0.32,
        duration: 260,
        tickInterval: 3,
        spreadChance: 0.015,
        maxAcidParticles: 160,
    },
    glueTool: {
        radius: 30,
        pinDuration: 600,
        bridgeMaxDistance: 140,
        temporarySpringHp: 60,
        maxGluePins: 30,
        maxGlueBridges: 20,
    },
    electricTool: {
        startRadius: 45,
        maxDepth: 8,
        maxNodes: 120,
        baseDamage: 22,
        falloff: 0.82,
        stunFrames: 20,
        arcParticlesPerLink: 2,
        cooldownMs: 500,
    },
    defaultMission: 'freeSandbox',
};

export function createDefaultConfig() {
    return typeof structuredClone === 'function' ? structuredClone(baseConfig) : JSON.parse(JSON.stringify(baseConfig));
}

export const config = createDefaultConfig();

export const configLimits = {
    numeroDeLinhas: { min: 5, max: 100, step: 1 },
    spacing: { min: 5, max: 50, step: 1 },
    stiffness: { min: 0.01, max: 1, step: 0.01 },
    gravity: { min: 0, max: 2, step: 0.01 },
    friction: { min: 0.8, max: 0.999, step: 0.001 },
    tearDistance: { min: 10, max: 200, step: 1 },
    lineWidth: { min: 0.1, max: 5, step: 0.1 },
    flameIntensity: { min: 0.1, max: 2.0, step: 0.1 },
};

export const defaultConfig = createDefaultConfig();

